Pop-up Window
RitaDee/portfolio pull request #20
Opened 2023-01-05 20:20 UTC by RitaDee

### In this milestone, we implemented the following:

- Used JavaScript array to store all of the information for all projects.
- Updated the main page so that the projects section is created dynamically using the information stored in the JavaScript object. 
- Implemented the popup window for both the desktop and mobile versions.

2023-01-05 21:33 UTC, levy002 requested changes
## Hello @RitaDee   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights 
- Excellent UI :heavy_check_mark: 
- All linters are green :heavy_check_mark: 
- Good commit history :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure on the desktop version user can be able to see the `See Project` button maybe by hovering over the project card. At this moment we are not able to other rest five card details pop-up. Kindly fix that. :wink: 

    - **YOUR APP BEHAVIOUR**
    
     ![chrome-capture-2023-0-5 (1)](https://user-images.githubusercontent.com/87197412/210883676-21a4503f-0131-486a-ace4-e25542b19494.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly make sure to add all contributors in the `Authors` section to your README file. :wink: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 21:33 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure your modal container has a background that is identical to the one in the provided Figma design.
 
    - **YOUR DESIGN**
      ![image](https://user-images.githubusercontent.com/87197412/210881214-40d05e26-f9f0-470a-8974-7876e410ca43.png)

    - **FIGMA DESIGN**
    
      ![image](https://user-images.githubusercontent.com/87197412/210881327-f1e121d1-4cb8-4853-8bee-b142c6eab140.png)

2023-01-05 21:33 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure your button contents are centered in order to meet the provided Figma design :wink:

    - **YOUR DESIGN**
     ![image](https://user-images.githubusercontent.com/87197412/210881744-bc8ff279-1f63-4fe8-9ec9-61c77daed802.png)

    - **FIGMA DESIGN**
   ![image](https://user-images.githubusercontent.com/87197412/210881789-3740b9ba-93ff-4f7a-bc41-0be03af59765.png)

2023-01-05 21:33 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure to provide enough space between the stack technologies I order to look like the provided Figma design. :wink:

     - **YOUR DESIGN**
     ![image](https://user-images.githubusercontent.com/87197412/210882303-9f8261d1-67ab-4ebc-a55c-32b207b112f9.png)

     - **FIGMA DESIGN**
     ![image](https://user-images.githubusercontent.com/87197412/210882375-b0030a89-8949-48c1-b579-a42a1dab0e8a.png)

2023-01-06 16:51 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :
Hi @RitaDee , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

<img src="https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif">

 ## Highlights :tophat: :+1: 
- Good use of Github flow :+1: 
- No linter errors :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions :ringed_planet: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 16:51 UTC, GedeonTS commented on style.css
> +
- [ ] Please make sure to remove these commented-out lines of code you just added to make your project cleaner :recycle:

2023-01-06 16:51 UTC, GedeonTS commented on style.css
> +  }
- [ ] Good job adding the see project button on hover effect as suggest by the previous reviewer [here](https://github.com/RitaDee/portfolio/pull/20#:~:text=Kindly%20make%20sure%20on%20the%20desktop%20version%20user%20can%20be%20able%20to%20see%20the%20See%20Project%20button%20maybe%20by%20hovering%20over%20the%20project%20card.%20At%20this%20moment%20we%20are%20not%20able%20to%20other%20rest%20five%20card) :clap: , however, while doing you have changed your design, please make it look back like the Figma design :record_button: 

Your current design:
![YourStacks](https://user-images.githubusercontent.com/97834160/211058717-a112e07b-0a12-4812-b151-0671296cd906.png)

Your previous & figma:
![figstacks](https://user-images.githubusercontent.com/97834160/211058797-55c7c9ed-3ad6-4c59-9474-91450a6e9116.png)

2023-01-06 18:23 UTC, Gopxfs approved these changes
# 🟢 STATUS: APPROVED 🟢

## Hello @RitaDee 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 18:25 UTC, merged